//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------

import { ServiceHelper } from '../../Infrastructure/Utilities/ServiceHelper';
import { ServiceLocator } from '../../Infrastructure/Locators/ServiceLocator';
import { Output, EventEmitter } from '@angular/core';
import { PropertyChangedArgs } from '../../Infrastructure/EventEmitterArgs/PropertyChangedArgs';
import { CustomFieldClass } from '../../Infrastructure/DataContracts/CustomFieldClass';

export class BatchServicesLogPM {
	constructor() {
		this.IsDirty = false;
	}

	private id: string;
	public get Id() {
		return this.id;
	}
	public set Id(newValue: string) {
		if (this.id != newValue) {
			this.id = newValue;
			this.MarkAsDirty('Id');
		}
	}

	private batchServiceCode: string;
	public get BatchServiceCode() {
		return this.batchServiceCode;
	}
	public set BatchServiceCode(newValue: string) {
		if (this.batchServiceCode != newValue) {
			this.batchServiceCode = newValue;
			this.MarkAsDirty('BatchServiceCode');
		}
	}

	private lastActivity: Date;
	public get LastActivity() {
		return this.lastActivity;
	}
	public set LastActivity(newValue: Date) {
		if (this.lastActivity != newValue) {
			this.lastActivity = newValue;
			this.MarkAsDirty('LastActivity');
		}
	}

	private cPU: number;
	public get CPU() {
		return this.cPU;
	}
	public set CPU(newValue: number) {
		if (this.cPU != newValue) {
			this.cPU = newValue;
			this.MarkAsDirty('CPU');
		}
	}

	private createDate: Date;
	public get CreateDate() {
		return this.createDate;
	}
	public set CreateDate(newValue: Date) {
		if (this.createDate != newValue) {
			this.createDate = newValue;
			this.MarkAsDirty('CreateDate');
		}
	}

	private numberOfDoneItems: number;
	public get NumberOfDoneItems() {
		return this.numberOfDoneItems;
	}
	public set NumberOfDoneItems(newValue: number) {
		if (this.numberOfDoneItems != newValue) {
			this.numberOfDoneItems = newValue;
			this.MarkAsDirty('NumberOfDoneItems');
		}
	}

	private doneItemsInOneHour: number;
	public get DoneItemsInOneHour() {
		return this.doneItemsInOneHour;
	}
	public set DoneItemsInOneHour(newValue: number) {
		if (this.doneItemsInOneHour != newValue) {
			this.doneItemsInOneHour = newValue;
			this.MarkAsDirty('DoneItemsInOneHour');
		}
	}

	private doneItemsInFiveMinutes: number;
	public get DoneItemsInFiveMinutes() {
		return this.doneItemsInFiveMinutes;
	}
	public set DoneItemsInFiveMinutes(newValue: number) {
		if (this.doneItemsInFiveMinutes != newValue) {
			this.doneItemsInFiveMinutes = newValue;
			this.MarkAsDirty('DoneItemsInFiveMinutes');
		}
	}

	private doneItemsInOneMinute: number;
	public get DoneItemsInOneMinute() {
		return this.doneItemsInOneMinute;
	}
	public set DoneItemsInOneMinute(newValue: number) {
		if (this.doneItemsInOneMinute != newValue) {
			this.doneItemsInOneMinute = newValue;
			this.MarkAsDirty('DoneItemsInOneMinute');
		}
	}

	private waitingItems: number;
	public get WaitingItems() {
		return this.waitingItems;
	}
	public set WaitingItems(newValue: number) {
		if (this.waitingItems != newValue) {
			this.waitingItems = newValue;
			this.MarkAsDirty('WaitingItems');
		}
	}

	private failedItems: number;
	public get FailedItems() {
		return this.failedItems;
	}
	public set FailedItems(newValue: number) {
		if (this.failedItems != newValue) {
			this.failedItems = newValue;
			this.MarkAsDirty('FailedItems');
		}
	}

	public OldEntityPM: BatchServicesLogPM;

	public IsDirty: boolean;
	public DisableMarkAsDirty: boolean = false;
	MarkAsDirty(propertyName: string = null) {
		if (!this.DisableMarkAsDirty) {
			this.IsDirty = true;

			if (propertyName != null) {
				ServiceLocator.RulesValidator.ApplyEntityChangedRules(propertyName, this, 'BatchServicesLog');
			}
		}
	}
	private MyClone: BatchServicesLogPM;

	public CloneMe() {
		ServiceHelper.CloneEntityPM(this);
	}

	public RejectChanges() {
		ServiceHelper.RejectEntityPMChanges(this);
	}
}
