//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------

import { ServiceHelper } from '../../Infrastructure/Utilities/ServiceHelper';
import { ServiceLocator } from '../../Infrastructure/Locators/ServiceLocator';
import { Output, EventEmitter } from '@angular/core';
import { PropertyChangedArgs } from '../../Infrastructure/EventEmitterArgs/PropertyChangedArgs';
import { CustomFieldClass } from '../../Infrastructure/DataContracts/CustomFieldClass';

export class BIReportPM {
	constructor() {
		this.IsDirty = false;
	}

	private id: string;
	public get Id() {
		return this.id;
	}
	public set Id(newValue: string) {
		if (this.id != newValue) {
			this.id = newValue;
			this.MarkAsDirty('Id');
		}
	}

	private tenant: number;
	public get Tenant() {
		return this.tenant;
	}
	public set Tenant(newValue: number) {
		if (this.tenant != newValue) {
			this.tenant = newValue;
			this.MarkAsDirty('Tenant');
		}
	}

	private createDate: Date;
	public get CreateDate() {
		return this.createDate;
	}
	public set CreateDate(newValue: Date) {
		if (this.createDate != newValue) {
			this.createDate = newValue;
			this.MarkAsDirty('CreateDate');
		}
	}

	private createdByUserId: string;
	public get CreatedByUserId() {
		return this.createdByUserId;
	}
	public set CreatedByUserId(newValue: string) {
		if (this.createdByUserId != newValue) {
			this.createdByUserId = newValue;
			this.MarkAsDirty('CreatedByUserId');
		}
	}

	private updateDate: Date;
	public get UpdateDate() {
		return this.updateDate;
	}
	public set UpdateDate(newValue: Date) {
		if (this.updateDate != newValue) {
			this.updateDate = newValue;
			this.MarkAsDirty('UpdateDate');
		}
	}

	private updatedByUserId: string;
	public get UpdatedByUserId() {
		return this.updatedByUserId;
	}
	public set UpdatedByUserId(newValue: string) {
		if (this.updatedByUserId != newValue) {
			this.updatedByUserId = newValue;
			this.MarkAsDirty('UpdatedByUserId');
		}
	}

	private searchFields: string;
	public get SearchFields() {
		return this.searchFields;
	}
	public set SearchFields(newValue: string) {
		if (this.searchFields != newValue) {
			this.searchFields = newValue;
			this.MarkAsDirty('SearchFields');
		}
	}

	private name: string;
	public get Name() {
		return this.name;
	}
	public set Name(newValue: string) {
		if (this.name != newValue) {
			this.name = newValue;
			this.MarkAsDirty('Name');
		}
	}

	private description: string;
	public get Description() {
		return this.description;
	}
	public set Description(newValue: string) {
		if (this.description != newValue) {
			this.description = newValue;
			this.MarkAsDirty('Description');
		}
	}

	private dWQueryId: string;
	public get DWQueryId() {
		return this.dWQueryId;
	}
	public set DWQueryId(newValue: string) {
		if (this.dWQueryId != newValue) {
			this.dWQueryId = newValue;
			this.MarkAsDirty('DWQueryId');
		}
	}

	private inactive: boolean;
	public get Inactive() {
		return this.inactive;
	}
	public set Inactive(newValue: boolean) {
		if (this.inactive != newValue) {
			this.inactive = newValue;
			this.MarkAsDirty('Inactive');
		}
	}

	private typeCode: string;
	public get TypeCode() {
		return this.typeCode;
	}
	public set TypeCode(newValue: string) {
		if (this.typeCode != newValue) {
			this.typeCode = newValue;
			this.MarkAsDirty('TypeCode');
		}
	}

	private aGGridOptionsXML: string;
	public get AGGridOptionsXML() {
		return this.aGGridOptionsXML;
	}
	public set AGGridOptionsXML(newValue: string) {
		if (this.aGGridOptionsXML != newValue) {
			this.aGGridOptionsXML = newValue;
			this.MarkAsDirty('AGGridOptionsXML');
		}
	}

	private bIReportFolderId: string;
	public get BIReportFolderId() {
		return this.bIReportFolderId;
	}
	public set BIReportFolderId(newValue: string) {
		if (this.bIReportFolderId != newValue) {
			this.bIReportFolderId = newValue;
			this.MarkAsDirty('BIReportFolderId');
		}
	}

	private createdByUserName: string;
	public get CreatedByUserName() {
		return this.createdByUserName;
	}
	public set CreatedByUserName(newValue: string) {
		if (this.createdByUserName != newValue) {
			this.createdByUserName = newValue;
			this.MarkAsDirty('CreatedByUserName');
		}
	}

	private updatedByUserName: string;
	public get UpdatedByUserName() {
		return this.updatedByUserName;
	}
	public set UpdatedByUserName(newValue: string) {
		if (this.updatedByUserName != newValue) {
			this.updatedByUserName = newValue;
			this.MarkAsDirty('UpdatedByUserName');
		}
	}

	private lastRunDate: Date;
	public get LastRunDate() {
		return this.lastRunDate;
	}
	public set LastRunDate(newValue: Date) {
		if (this.lastRunDate != newValue) {
			this.lastRunDate = newValue;
			this.MarkAsDirty('LastRunDate');
		}
	}

	private lastRunByUserName: string;
	public get LastRunByUserName() {
		return this.lastRunByUserName;
	}
	public set LastRunByUserName(newValue: string) {
		if (this.lastRunByUserName != newValue) {
			this.lastRunByUserName = newValue;
			this.MarkAsDirty('LastRunByUserName');
		}
	}

	private factTableName: string;
	public get FactTableName() {
		return this.factTableName;
	}
	public set FactTableName(newValue: string) {
		if (this.factTableName != newValue) {
			this.factTableName = newValue;
			this.MarkAsDirty('FactTableName');
		}
	}

	private lastRunId: string;
	public get LastRunId() {
		return this.lastRunId;
	}
	public set LastRunId(newValue: string) {
		if (this.lastRunId != newValue) {
			this.lastRunId = newValue;
			this.MarkAsDirty('LastRunId');
		}
	}

	public OldEntityPM: BIReportPM;

	public IsDirty: boolean;
	public DisableMarkAsDirty: boolean = false;
	MarkAsDirty(propertyName: string = null) {
		if (!this.DisableMarkAsDirty) {
			this.IsDirty = true;

			if (propertyName != null) {
				ServiceLocator.RulesValidator.ApplyEntityChangedRules(propertyName, this, 'BIReport');
			}
		}
	}

	private MyClone: BIReportPM;

	public CloneMe() {
		ServiceHelper.CloneEntityPM(this);
	}

	public RejectChanges() {
		ServiceHelper.RejectEntityPMChanges(this);
	}
}
