//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------

import { BIFoldersPermissionPM } from './BIFoldersPermissionPM';

import { ServiceHelper } from '../../Infrastructure/Utilities/ServiceHelper';
import { ServiceLocator } from '../../Infrastructure/Locators/ServiceLocator';
import { Output, EventEmitter } from '@angular/core';
import { PropertyChangedArgs } from '../../Infrastructure/EventEmitterArgs/PropertyChangedArgs';
import { CustomFieldClass } from '../../Infrastructure/DataContracts/CustomFieldClass';

export class BIReportFolderPM {
	constructor() {
		this.IsDirty = false;
	}

	private id: string;
	public get Id() {
		return this.id;
	}
	public set Id(newValue: string) {
		if (this.id != newValue) {
			this.id = newValue;
			this.MarkAsDirty('Id');
		}
	}

	private tenant: number;
	public get Tenant() {
		return this.tenant;
	}
	public set Tenant(newValue: number) {
		if (this.tenant != newValue) {
			this.tenant = newValue;
			this.MarkAsDirty('Tenant');
		}
	}

	private createDate: Date;
	public get CreateDate() {
		return this.createDate;
	}
	public set CreateDate(newValue: Date) {
		if (this.createDate != newValue) {
			this.createDate = newValue;
			this.MarkAsDirty('CreateDate');
		}
	}

	private createdByUserId: string;
	public get CreatedByUserId() {
		return this.createdByUserId;
	}
	public set CreatedByUserId(newValue: string) {
		if (this.createdByUserId != newValue) {
			this.createdByUserId = newValue;
			this.MarkAsDirty('CreatedByUserId');
		}
	}

	private updateDate: Date;
	public get UpdateDate() {
		return this.updateDate;
	}
	public set UpdateDate(newValue: Date) {
		if (this.updateDate != newValue) {
			this.updateDate = newValue;
			this.MarkAsDirty('UpdateDate');
		}
	}

	private updatedByUserId: string;
	public get UpdatedByUserId() {
		return this.updatedByUserId;
	}
	public set UpdatedByUserId(newValue: string) {
		if (this.updatedByUserId != newValue) {
			this.updatedByUserId = newValue;
			this.MarkAsDirty('UpdatedByUserId');
		}
	}

	private searchFields: string;
	public get SearchFields() {
		return this.searchFields;
	}
	public set SearchFields(newValue: string) {
		if (this.searchFields != newValue) {
			this.searchFields = newValue;
			this.MarkAsDirty('SearchFields');
		}
	}

	private name: string;
	public get Name() {
		return this.name;
	}
	public set Name(newValue: string) {
		if (this.name != newValue) {
			this.name = newValue;
			this.MarkAsDirty('Name');
		}
	}

	private description: string;
	public get Description() {
		return this.description;
	}
	public set Description(newValue: string) {
		if (this.description != newValue) {
			this.description = newValue;
			this.MarkAsDirty('Description');
		}
	}

	private index: number;
	public get Index() {
		return this.index;
	}
	public set Index(newValue: number) {
		if (this.index != newValue) {
			this.index = newValue;
			this.MarkAsDirty('Index');
		}
	}

	private createdByUserName: string;
	public get CreatedByUserName() {
		return this.createdByUserName;
	}
	public set CreatedByUserName(newValue: string) {
		if (this.createdByUserName != newValue) {
			this.createdByUserName = newValue;
			this.MarkAsDirty('CreatedByUserName');
		}
	}

	private updatedByUserName: string;
	public get UpdatedByUserName() {
		return this.updatedByUserName;
	}
	public set UpdatedByUserName(newValue: string) {
		if (this.updatedByUserName != newValue) {
			this.updatedByUserName = newValue;
			this.MarkAsDirty('UpdatedByUserName');
		}
	}

	private permissionForAll: boolean;
	public get PermissionForAll() {
		return this.permissionForAll;
	}
	public set PermissionForAll(newValue: boolean) {
		if (this.permissionForAll != newValue) {
			this.permissionForAll = newValue;
			this.MarkAsDirty('PermissionForAll');
		}
	}

	private permittedByUserId: string;
	public get PermittedByUserId() {
		return this.permittedByUserId;
	}
	public set PermittedByUserId(newValue: string) {
		if (this.permittedByUserId != newValue) {
			this.permittedByUserId = newValue;
			this.MarkAsDirty('PermittedByUserId');
		}
	}

	private permittedBIFolders: BIFoldersPermissionPM[];
	get PermittedBIFolders() {
		if (this.permittedBIFolders == null) {
			this.permittedBIFolders = [];
		}

		return this.permittedBIFolders;
	}
	set PermittedBIFolders(newValue: BIFoldersPermissionPM[]) {
		if (this.permittedBIFolders != newValue) {
			this.permittedBIFolders = newValue;
		}
	}
	public AddBIFoldersPermission(item: BIFoldersPermissionPM) {
		if (item != null) {
			var index = this.PermittedBIFolders.indexOf(item);
			if (index == -1) {
				item.EntityParentPM = this;
				this.PermittedBIFolders.push(item);
				this.MarkAsDirty();
			}
		}
	}
	public RemoveBIFoldersPermission(item: BIFoldersPermissionPM) {
		if (item != null) {
			var index = this.PermittedBIFolders.indexOf(item);
			if (index > -1) {
				this.PermittedBIFolders.splice(index, 1);
				this.MarkAsDirty();
			}
		}
	}
	//public PermittedBIFolders: Array<BIFoldersPermissionPM>= [];

	public OldEntityPM: BIReportFolderPM;

	public IsDirty: boolean;
	public DisableMarkAsDirty: boolean = false;
	MarkAsDirty(propertyName: string = null) {
		if (!this.DisableMarkAsDirty) {
			this.IsDirty = true;

			if (propertyName != null) {
				ServiceLocator.RulesValidator.ApplyEntityChangedRules(propertyName, this, 'BIReportFolder');
			}
		}
	}

	private MyClone: BIReportFolderPM;

	public CloneMe() {
		ServiceHelper.CloneEntityPM(this);
	}

	public RejectChanges() {
		ServiceHelper.RejectEntityPMChanges(this);
	}
}
