//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------

import { ServiceHelper } from '../../Infrastructure/Utilities/ServiceHelper';
import { ServiceLocator } from '../../Infrastructure/Locators/ServiceLocator';
import { Output, EventEmitter } from '@angular/core';
import { PropertyChangedArgs } from '../../Infrastructure/EventEmitterArgs/PropertyChangedArgs';
import { CustomFieldClass } from '../../Infrastructure/DataContracts/CustomFieldClass';

export class IATACodePM {
	constructor() {
		this.IsDirty = false;
	}

	private id: string;
	public get Id() {
		return this.id;
	}
	public set Id(newValue: string) {
		if (this.id != newValue) {
			this.id = newValue;
			this.MarkAsDirty('Id');
		}
	}

	private code: string;
	public get Code() {
		return this.code;
	}
	public set Code(newValue: string) {
		if (this.code != newValue) {
			this.code = newValue;
			this.MarkAsDirty('Code');
		}
	}

	private name: string;
	public get Name() {
		return this.name;
	}
	public set Name(newValue: string) {
		if (this.name != newValue) {
			this.name = newValue;
			this.MarkAsDirty('Name');
		}
	}

	private searchFields: string;
	public get SearchFields() {
		return this.searchFields;
	}
	public set SearchFields(newValue: string) {
		if (this.searchFields != newValue) {
			this.searchFields = newValue;
			this.MarkAsDirty('SearchFields');
		}
	}

	private measurementCode: string;
	public get MeasurementCode() {
		return this.measurementCode;
	}
	public set MeasurementCode(newValue: string) {
		if (this.measurementCode != newValue) {
			this.measurementCode = newValue;
			this.MarkAsDirty('MeasurementCode');
		}
	}

	private dueTypeCode: string;
	public get DueTypeCode() {
		return this.dueTypeCode;
	}
	public set DueTypeCode(newValue: string) {
		if (this.dueTypeCode != newValue) {
			this.dueTypeCode = newValue;
			this.MarkAsDirty('DueTypeCode');
		}
	}

	private isIATA: boolean;
	public get IsIATA() {
		return this.isIATA;
	}
	public set IsIATA(newValue: boolean) {
		if (this.isIATA != newValue) {
			this.isIATA = newValue;
			this.MarkAsDirty('IsIATA');
		}
	}

	private inActive: boolean;
	public get InActive() {
		return this.inActive;
	}
	public set InActive(newValue: boolean) {
		if (this.inActive != newValue) {
			this.inActive = newValue;
			this.MarkAsDirty('InActive');
		}
	}

	private airlineId: string;
	public get AirlineId() {
		return this.airlineId;
	}
	public set AirlineId(newValue: string) {
		if (this.airlineId != newValue) {
			this.airlineId = newValue;
			this.MarkAsDirty('AirlineId');
		}
	}

	public OldEntityPM: IATACodePM;

	public IsDirty: boolean;
	public DisableMarkAsDirty: boolean = false;
	MarkAsDirty(propertyName: string = null) {
		if (!this.DisableMarkAsDirty) {
			this.IsDirty = true;

			if (propertyName != null) {
				ServiceLocator.RulesValidator.ApplyEntityChangedRules(propertyName, this, 'IATACode');
			}
		}
	}
	private MyClone: IATACodePM;

	public CloneMe() {
		ServiceHelper.CloneEntityPM(this);
	}

	public RejectChanges() {
		ServiceHelper.RejectEntityPMChanges(this);
	}
}
