//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------

export class TransportModePM {
	constructor() {
		this.UIProperties = new UIProperties();
		this.IsDirty = false;
	}

	private id: string;
	public get Id() {
		return this.id;
	}
	public set Id(newValue: string) {
		this.id = newValue;
		this.MarkAsDirty();
	}

	private name: string;
	public get Name() {
		return this.name;
	}
	public set Name(newValue: string) {
		this.name = newValue;
		this.MarkAsDirty();
	}

	private searchFields: string;
	public get SearchFields() {
		return this.searchFields;
	}
	public set SearchFields(newValue: string) {
		this.searchFields = newValue;
		this.MarkAsDirty();
	}

	public OldEntityPM: TransportModePM;

	public IsDirty: boolean;
	MarkAsDirty() {
		this.IsDirty = true;
	}
}
