//------------------------------------------------------------------------------
// <auto-generated>
//     Angular 9.1.1
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { Injectable } from '@angular/core';
import { HttpClient, HttpResponse } from '@angular/common/http';
import { catchError, map } from 'rxjs/operators';
import { defer, of } from 'rxjs';
import {ServiceResponse} from '../../DataContracts/ServiceResponse';
import {ClassLevelValidator} from '../../Validators/ClassLevelValidator';
import {Guid} from '../../Utilities/Guid';
import {InfraSettings} from '../../Utilities/InfraSettings';
import {ServiceHelper} from '../../Utilities/ServiceHelper';
import {SessionInfo} from '../../Utilities/SessionInfo';
import {PerformanceLogger} from '../../Utilities/PerformanceLogger';
import {CustomFieldClass} from '../../DataContracts/CustomFieldClass'

import {BIReportFolderPM} from '../../EntityPMs/BIReportFolderPM';

import {BIFoldersPermissionPM} from '../../EntityPMs/BIFoldersPermissionPM';

@Injectable()

export class BIReportFolderPMService {
 private _http: HttpClient;
 private _apiUrl: string;
 constructor() {
        this._http = ServiceHelper.HttpClient;
        this._apiUrl = ServiceHelper.GetLogitudeURL() + 'api/bireportfolders';      
    }

	get(id: string) {       

		var callTime = new Date();		

		return defer(() => {
			return this._http.get(this._apiUrl + '/getsingle?' + 'id=' + id, ServiceHelper.GetHttpFullHeaders())
				.pipe(
					map((response: HttpResponse<any>) => {
						var pm = response.body;
				
						var entity: BIReportFolderPM;
						if (pm) {
							entity = this.MapJsonToEntityPM(pm);
						}

						var serviceResponse: ServiceResponse = new ServiceResponse();
						serviceResponse.Result = entity;
              
						var servertime = response.headers.get('ServerExecutionTime');
						PerformanceLogger.InsertPerformanceLog(callTime, new Date(), Number(servertime), "BIReportFolder", "GetSinglePM", 'id=' + id);
				 
						return serviceResponse;

					}),
					
					catchError(ServiceHelper.HandleServiceError));
		});                    
	}

	insert(entityPM: BIReportFolderPM) {
 
		var callTime = new Date();  
		
		return defer(() => {

			var serviceResponse: ServiceResponse = new ServiceResponse();
			var validator: ClassLevelValidator = new ClassLevelValidator();                
			var errorsArray = validator.Validate("BIReportFolder", entityPM);


			if (errorsArray.length == 0) {

				var mappedEntity: BIReportFolderPM = this.MapJsonToEntityPM(entityPM, false);
				
				return this._http.post(this._apiUrl, JSON.stringify(mappedEntity), ServiceHelper.GetHttpFullHeaders())
					.pipe(
						map((response: HttpResponse<any>) => {

							var pm = response.body;
							if (pm) {
								var mappedResult: BIReportFolderPM = this.MapJsonToEntityPM(pm, true, entityPM);
								serviceResponse.Result = mappedResult;
							}						

							var servertime = response.headers.get('ServerExecutionTime');
							PerformanceLogger.InsertPerformanceLog(callTime, new Date(), Number(servertime), "BIReportFolder", "SaveChanges", "");                    
												                             
							return serviceResponse;
						}),

						catchError(ServiceHelper.HandleServiceError));
			}

			else {
				serviceResponse.HasError = true;
				serviceResponse.ErrorsArray = errorsArray;
				return of(serviceResponse);
			}
		});
	}

	update(entityPM: BIReportFolderPM) {

		var callTime = new Date();     
		
		return defer(() => {

			var serviceResponse: ServiceResponse = new ServiceResponse();
			var validator: ClassLevelValidator = new ClassLevelValidator();               
			var errorsArray = validator.Validate("BIReportFolder", entityPM);


			if (errorsArray.length == 0) {

				var mappedEntity: BIReportFolderPM = this.MapJsonToEntityPM(entityPM, false);
				
				return this._http.put(this._apiUrl, JSON.stringify(mappedEntity), ServiceHelper.GetHttpFullHeaders())
					.pipe(
						map((response: HttpResponse<any>) => {
                 
							var pm = response.body;
							if (pm) {
								var mappedResult: BIReportFolderPM = this.MapJsonToEntityPM(pm, true, entityPM);
								serviceResponse.Result = mappedResult;
							}
							 
							var servertime = response.headers.get('ServerExecutionTime');
							PerformanceLogger.InsertPerformanceLog(callTime, new Date(), Number(servertime), "BIReportFolder", "SaveChanges", "");                    
					                           
							return serviceResponse;
						}),

						catchError(ServiceHelper.HandleServiceError));
			}

			else {
				serviceResponse.HasError = true;
				serviceResponse.ErrorsArray = errorsArray;
				return of(serviceResponse);
			}
		});
	}

   

	  MapJsonToEntityPM(jsonPM: any, mapParent: boolean = true, entityPM: BIReportFolderPM = null) {

         
        if (!entityPM) {
            
            entityPM = new BIReportFolderPM();
			entityPM.DisableMarkAsDirty = true;
        }

		var customFields: Array<string> = [];
        for (var i = 1; i < 11; i++) {
            customFields.push("Field" + i);
        }
            var jsonPMKeys = Object.keys(jsonPM);

            for (var key in jsonPMKeys) {
			 if (jsonPMKeys[key] === "UIProperties" || jsonPMKeys[key] === "PropertyChanged") {

                continue;
            }
                var property = jsonPMKeys[key];
				
			  if(customFields.indexOf(property) > -1)
                {
                if (jsonPM[property]) {
                    var customFieldClass: CustomFieldClass = new CustomFieldClass(jsonPM[property].Value, jsonPM[property].FieldName, jsonPM[property].TableName);
                    entityPM[property] = customFieldClass;
                }
            }
            else {
                entityPM[property] = jsonPM[property];
            }
                 
            }
			
               this.MapPermittedBIFolders(entityPM, jsonPM, mapParent); // Call composition tables map methods
			 
            

		if (mapParent) {
                entityPM.OldEntityPM = this.clone(entityPM);
			   			   
            entityPM.OldEntityPM.PermittedBIFolders = [];
            for (var item in entityPM.PermittedBIFolders) {
            var myBIFoldersPermissionPM = entityPM.PermittedBIFolders[item];
            var newBIFoldersPermissionPM: BIFoldersPermissionPM = this.clone(myBIFoldersPermissionPM);
						
							 
            entityPM.OldEntityPM.PermittedBIFolders.push(newBIFoldersPermissionPM);
            }
			   
		}
        else {

            entityPM.OldEntityPM = null;
        }
		entityPM.IsDirty = false;
	    entityPM.DisableMarkAsDirty = false;

        return entityPM;
    }

    MapPermittedBIFolders(entityPM: BIReportFolderPM, jsonPM: any, mapParent: boolean = true) {

        var oldPermittedBIFolders: BIFoldersPermissionPM[] = [];
        if (entityPM.OldEntityPM && !mapParent) {
            oldPermittedBIFolders = entityPM.OldEntityPM.PermittedBIFolders;
        }

        entityPM.PermittedBIFolders = new Array<BIFoldersPermissionPM>();
        for (var item in jsonPM.PermittedBIFolders) {
            var jItem = jsonPM.PermittedBIFolders[item];
            if (mapParent && (jItem.ChangeSetOp == "Delete" || jItem.ChangeSetOp == 3)) {
                continue;
            }
            var newBIFoldersPermissionPM: BIFoldersPermissionPM;
	  
            if (mapParent) {
                newBIFoldersPermissionPM = new BIFoldersPermissionPM(entityPM);
            }
            else
            {
                newBIFoldersPermissionPM = new BIFoldersPermissionPM(null);
            }
 			newBIFoldersPermissionPM.DisableMarkAsDirty = true;
               
            var pmKeysArray = Object.keys(jItem);
            for (var pmKey in pmKeysArray) {
                if ((!mapParent && pmKeysArray[pmKey] === "entityParentPM" )|| pmKeysArray[pmKey] === "UIProperties" || pmKeysArray[pmKey] === "PropertyChanged") {
                    continue;
                }
                var pmProperty = pmKeysArray[pmKey];
                newBIFoldersPermissionPM[pmProperty] = jItem[pmProperty];
            }
           
			 
            if (mapParent) {
                newBIFoldersPermissionPM.UniqueKey = Guid.newGuid();
                newBIFoldersPermissionPM.ChangeSetOp = "None";
                jItem.ChangeSetOp = "None";
                newBIFoldersPermissionPM.OldEntityPM = this.clone(newBIFoldersPermissionPM);

				
            }
            else {
                if (newBIFoldersPermissionPM.UniqueKey) {

                    if (jItem.IsDirty)
                        newBIFoldersPermissionPM.ChangeSetOp = "Update";
                }
                else {
                        newBIFoldersPermissionPM.ChangeSetOp = "Insert";
                }
 
                newBIFoldersPermissionPM.OldEntityPM = null;
                newBIFoldersPermissionPM.EntityParentPM = null;
            }
			 newBIFoldersPermissionPM.DisableMarkAsDirty = false;
			 newBIFoldersPermissionPM.IsDirty = false;
            entityPM.PermittedBIFolders.push(newBIFoldersPermissionPM);
        }
        if (oldPermittedBIFolders) {
            
            for (var itemKey in oldPermittedBIFolders) {
                if (entityPM.PermittedBIFolders.filter(p=> p.UniqueKey === oldPermittedBIFolders[itemKey].UniqueKey).length === 0) {
				
                    if (oldPermittedBIFolders[itemKey]) {
                        //oldPermittedBIFolders[itemKey].ChangeSetOp = "Delete";
                        //entityPM.PermittedBIFolders.push(oldPermittedBIFolders[itemKey]);
						var oldItemJson = oldPermittedBIFolders[itemKey];
                        var deletedPM: BIFoldersPermissionPM = new BIFoldersPermissionPM(null);
						deletedPM.DisableMarkAsDirty = true;
                        var pmKeys = Object.keys(oldItemJson);
                        for (var key in pmKeys) {

                            if ((!mapParent && pmKeys[key] === "entityParentPM") || pmKeys[key] === "UIProperties" || pmKeys[key] === "OldEntityPM" || pmKeys[key] === "PropertyChanged") {
                                continue;
                            }

                            var property = pmKeys[key];
                            deletedPM[property] = oldItemJson[property];
                        }

					    deletedPM.DisableMarkAsDirty = false;
                        deletedPM.IsDirty = false;
                        deletedPM.ChangeSetOp = "Delete";
                        
                        deletedPM.OldEntityPM = null;
                        entityPM.PermittedBIFolders.push(deletedPM);
                    }
                }
            }
        }
    }

	  public clone(jsonPM: any) {
        var entityPM: any;
        entityPM = {};

        var jsonPMKeys = Object.keys(jsonPM);
        for (var key in jsonPMKeys) {
            
            if ((jsonPMKeys[key] === "entityParentPM") || jsonPMKeys[key] === "UIProperties" || jsonPMKeys[key] === "OldEntityPM" || jsonPMKeys[key] === "PropertyChanged") {
                continue;
            }

            var property = jsonPMKeys[key];
            entityPM[property] = jsonPM[property];

        }
        return entityPM;
    }

	  public GetNewEntityPM() {		 
		    var entityPM: BIReportFolderPM;
			entityPM = new BIReportFolderPM();
			entityPM.Tenant = InfraSettings.TenantPM.Id;
			return entityPM;
    }
		 

}
