//------------------------------------------------------------------------------
// <auto-generated>
//     Angular 9.1.1
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { Injectable } from '@angular/core';
import { HttpClient, HttpResponse } from '@angular/common/http';
import { catchError, map } from 'rxjs/operators';
import { defer, of } from 'rxjs';
import {ApiQueryFilters} from '../../DataContracts/ApiQueryFilters';
import {ServiceResponse} from '../../DataContracts/ServiceResponse';
import {InfraGenericFilter} from '../../Utilities/InfraGenericFilter';
import {CachedDataManager} from '../../Utilities/CachedDataManager';
import {ServiceHelper} from '../../Utilities/ServiceHelper';
import {SessionLocator} from '../../Utilities/SessionLocator';
import {SessionInfo} from '../../Utilities/SessionInfo';
import {LocalStorageManager} from '../../Utilities/LocalStorageManager';
import {PerformanceLogger} from '../../Utilities/PerformanceLogger';
import {PrepaidCollectList} from '../../EntityLists/PrepaidCollectList';

@Injectable()

export class PrepaidCollectListService {
	private _http: HttpClient;
    private _apiUrl: string;   
	public static CachedData: Array<PrepaidCollectList> = [];
    constructor() {
        this._http = ServiceHelper.HttpClient;
        this._apiUrl = ServiceHelper.GetLogitudeURL() + 'api/prepaidcollectviews';  
    }

	getSingle(id: string) {

		var callTime = new Date();

		return defer(() => {
			return this._http.get(this._apiUrl + '/getsingle/?' + 'id=' + id, ServiceHelper.GetHttpFullHeaders())
				.pipe(
					map((response: HttpResponse<any>) => {

						var list = response.body;                    
						var entity: PrepaidCollectList;
						if (list) {
							entity = this.MapJsonToEntityList(list);
						}

						var serviceResponse: ServiceResponse = new ServiceResponse(); 
						serviceResponse.Result = entity;  
						serviceResponse.CallTime = callTime;

						var servertime = response.headers.get('ServerExecutionTime');
						PerformanceLogger.InsertPerformanceLog(callTime, new Date(), Number(servertime), "PrepaidCollect", "GetSingleList", 'id=' + id); 

						return serviceResponse;
					}),
					
					catchError(ServiceHelper.HandleServiceError));
		});
	}

	getAll() {

		var callTime = new Date();

		return defer(() => {
			return this._http.get(this._apiUrl + '/getall', ServiceHelper.GetHttpFullHeaders())
				.pipe(
					map((response: HttpResponse<any>) => {

						var allLists = response.body;
						var _mappedListsArray: Array<PrepaidCollectList> = [];
						if (allLists) {
							for (var key in allLists) {			
								var entity: PrepaidCollectList = this.MapJsonToEntityList(allLists[key]);
								_mappedListsArray.push(entity);
							}
						}

						var serviceResponse: ServiceResponse = new ServiceResponse(); 
						serviceResponse.Result = _mappedListsArray;  
						serviceResponse.CallTime = callTime;

						var servertime = response.headers.get('ServerExecutionTime');
						PerformanceLogger.InsertPerformanceLog(callTime, new Date(), Number(servertime), "PrepaidCollect", "GetAll", ""); 

						return serviceResponse;
					}),

					catchError(ServiceHelper.HandleServiceError));
		});
	}
	
	getByFilters(filters: ApiQueryFilters) {

		var callTime = new Date();       
		var urlparameters = '/getbyfilters?';
        var mykeys = Object.keys(filters);
        var addtionalFiltersValues = null;

        for (var i in mykeys) {
			var propName = mykeys[i];
			var propValue = filters[propName];
			var ignoreFilter = ((propName.indexOf("Operator") > 0 && propValue == "Equals") || propName == "AdditionalFilters");

            if (urlparameters != "?") {
                urlparameters = urlparameters.concat('&');
            }

			if (!ignoreFilter) {
				propValue = encodeURIComponent(propValue);
				urlparameters = urlparameters.concat(propName.concat('=').concat(propValue));
			}

			if (propName == "AdditionalFilters" && propValue.length > 0) {
				addtionalFiltersValues = JSON.stringify(propValue);
			}
        }

        if (addtionalFiltersValues) {
            urlparameters = urlparameters.concat("&AdditionalFilters=").concat(addtionalFiltersValues);
        }

		var callUrl = this._apiUrl.concat(urlparameters);
        		
		return defer(() => {
			return this._http.get(callUrl, ServiceHelper.GetHttpFullHeaders())
				.pipe(
					map((response: HttpResponse<any>) => {

						var serviceResponse: ServiceResponse = response.body;
						var _mappedListsArray: Array<PrepaidCollectList> = [];

						if (serviceResponse.Result) {
							for (var key in serviceResponse.Result) {				
								var entity: PrepaidCollectList = this.MapJsonToEntityList(serviceResponse.Result[key]);
								_mappedListsArray.push(entity);
							}
						}   

						serviceResponse.Result = _mappedListsArray;      
						serviceResponse.CallTime = callTime;

						var servertime = response.headers.get('ServerExecutionTime');
						PerformanceLogger.InsertPerformanceLog(callTime, new Date(), Number(servertime), "PrepaidCollect", "GetByFilters", "PageIndex:" +filters.PageIndex +", PageSize:"+filters.PageSize + ", GetAll:" + filters.GetAll); 
                 								            
						return serviceResponse;
					}),

					catchError(ServiceHelper.HandleServiceError));
		});
	}

	getSingleFromCache(id: string) {

		var callTime = new Date(); 	    

		if (!SessionLocator.UseCachedData) {
            return this.getSingle(id);
        }

        var serviceResponse: ServiceResponse = new ServiceResponse();

		if (PrepaidCollectListService.CachedData.length > 0) {
			return defer(() => {
				var filteredData = PrepaidCollectListService.CachedData.filter(a => a.Id === id)[0];
				serviceResponse.CallTime = callTime;
				serviceResponse.Result = filteredData; 
                return of(serviceResponse);
            });
        }

        else {
            return CachedDataManager.GetClosedTableData("PrepaidCollect").pipe(
				map((cachedJson:any) => {

					var _mappedListsArray: Array<PrepaidCollectList> = [];

					if (cachedJson) {
						for (var key in cachedJson) {
							var entity: PrepaidCollectList = this.MapJsonToEntityList(cachedJson[key]);
							_mappedListsArray.push(entity);
						}
					}

					PrepaidCollectListService.CachedData = _mappedListsArray;

					var filteredData = PrepaidCollectListService.CachedData.filter(a => a.Id === id)[0];
					serviceResponse.Result = filteredData; 
					serviceResponse.CallTime = callTime;
			     
					PerformanceLogger.InsertPerformanceLog(callTime, new Date(), 0, "PrepaidCollect", "GetSingleListFromCache", 'id=' + id); 

					return serviceResponse;
				}),

				catchError(ServiceHelper.HandleServiceError));
        }
    }

    getAllFromCache(filters: ApiQueryFilters= new ApiQueryFilters(true)) {

		var callTime = new Date();

		if (!SessionLocator.UseCachedData) {
			return this.getByFilters(filters);
        }

        var mykeys = Object.keys(filters);
        var addtionalFiltersValues = null;

        for (var i in mykeys) {
            var propName = mykeys[i];
            var propValue = filters[propName];

            if (propName == "AdditionalFilters" && propValue.length > 0) {
                addtionalFiltersValues = JSON.stringify(propValue);
			}
        }

        var serviceResponse: ServiceResponse = new ServiceResponse();

        if (PrepaidCollectListService.CachedData.length > 0) {
            return defer(() => {
                if (filters.GetAll) {
					serviceResponse.Result = PrepaidCollectListService.CachedData; 
				}

				else {
					var filteredData = InfraGenericFilter.GetFilteredArray(PrepaidCollectListService.CachedData, filters);
					serviceResponse.Result = filteredData; 
					serviceResponse.CallTime = callTime;
				}

                return of(serviceResponse);
            });
        }

        else {
            return CachedDataManager.GetClosedTableData("PrepaidCollect").pipe(
				map((cachedJson:any) => {

					var _mappedListsArray: Array<PrepaidCollectList> = [];
					if (cachedJson) {
						for (var key in cachedJson) {
							var entity: PrepaidCollectList = this.MapJsonToEntityList(cachedJson[key]);
							_mappedListsArray.push(entity);
						}
					}

					PrepaidCollectListService.CachedData = _mappedListsArray;

					if (filters.GetAll) {
						serviceResponse.Result = _mappedListsArray; 
					}

					else {

						_mappedListsArray = InfraGenericFilter.GetFilteredArray(_mappedListsArray, filters);

						PerformanceLogger.InsertPerformanceLog(callTime, new Date(), 0, "PrepaidCollect", "GetAllFromCache", "PageIndex:" + filters.PageIndex + ", PageSize:" + filters.PageSize + ", GetAll:" + filters.GetAll); 
                 	
						serviceResponse.Result = _mappedListsArray; 
						serviceResponse.CallTime = callTime;
					}

					return serviceResponse;
				}),
			
				catchError(ServiceHelper.HandleServiceError));
        }		 
    }
	
	    MapJsonToEntityList(jsonList: any) {
       
            var entityList: PrepaidCollectList;
            entityList = new PrepaidCollectList();
            var jsonListKeys = Object.keys(jsonList);

            for (var key in jsonListKeys) {
                var property = jsonListKeys[key];
                entityList[property] = jsonList[property];
            }
			

        return entityList;
    }

}

