//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class APILogsList {
   		Id: string;
		Tenant: number;
		Direction: string;
		Status: string;
		CreateDate: Date;
		CreateDateUTC: Date;
		LastUpdateDate: Date;
		LastUpdateDateUTC: Date;
		NumberOfRetries: number;
		ExpirationDate: Date;
		Subject: string;
		EntityId: string;
		ObjectTableId: string;
		PartnerName: string;
		Refrence: string;
		SearchFields: string;
		LastExceptionMessage: string;
		CorrelationId: string;
		DiagnosticLog: string;
		BodyData: string;
		ExceptionsMessage: string;
		StatusName: string;
		BatchNumber: string;
		CustomerId: string;
		ObjectTableName: string;
	
}