//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class BatchTaskExecutionList {
   
	Id: string;
	Tenant: number;
	CreateDate: Date;
	CreatedByUserId: string;
	SearchFields: string;
	ClassName: string;
	PrametersXml: string;
	StatusCode: string;
	ErrorLog: string;
	StartDateTime: Date;
	DoneDateTime: Date;
	ProgressMessage: string;
	ProgressPercentage: number;
	StatusName: string;
	CreatedByUserName: string;
	Subject: string;
	CallStack: string;
	
}
 