//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class BatchServicesLogList {
   		Id: string;
		BatchServiceCode: string;
		LastActivity: Date;
		CPU: number;
		CreateDate: Date;
		NumberOfDoneItems: number;
		DoneItemsInOneHour: number;
		DoneItemsInOneMinute: number;
		DoneItemsInFiveMinutes: number;
		WaitingItems: number;
		FailedItems: number;
	
}