//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class BluesnapContractList {
   		Id: string;
		Code: string;
		Name: string;
		ContractId: string;
		SearchFields: string;
		InActive: boolean;
		BluesnapContractTypeCode: string;
		BluesnapContractTypeName: string;
	
}