//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class BusinessHourList {
   		Id: string;
		Tenant: number;
		Code: string;
		Name: string;
		Description: string;
		Is247: boolean;
		CreatedByUserId: string;
		UpdatedByUserId: string;
		CreateDate: Date;
		UpdateDate: Date;
		IsMondayEnabeled: boolean;
		IsTuesdayEnabeled: boolean;
		IsWednesdayEnabeled: boolean;
		IsThursdayEnabeled: boolean;
		IsFridayEnabeled: boolean;
		IsSaturdayEnabeled: boolean;
		IsSundayEnabeled: boolean;
		MondayFromHour: string;
		TuesdayFromHour: string;
		WednesdayFromHour: string;
		ThursdayFromHour: string;
		FridayFromHour: string;
		SaturdayFromHour: string;
		SundayFromHour: string;
		MondayToHour: string;
		TuesdayToHour: string;
		WednesdayToHour: string;
		ThursdayToHour: string;
		FridayToHour: string;
		SaturdayToHour: string;
		SundayToHour: string;
		SearchFields: string;
	
}