//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class EmailAlertSettingList {
   		Id: string;
		Tenant: number;
		Code: string;
		Description: string;
		ObjectTableId: string;
		InActive: boolean;
		SettingLevelCode: string;
		To: string;
		IndexOrder: number;
	
}