//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class HelpResourceList {
   		Code: string;
		Name: string;
		CreateDate: Date;
		UpdateDate: Date;
		Language: string;
		Type: string;
		Category: string;
		VideoURL: string;
		Duration: string;
		FileName: string;
		SearchFields: string;
		IsNew: boolean;
		FeatureCode: string;
		Tenant: number;
		TypeName: string;
		CategoryName: string;
		Inactive: boolean;
	
}