//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class InboundEmailLineList {
   		Id: string;
		Tenant: number;
		Sender: string;
		Recepient: string;
		Subject: string;
		Body: string;
		FullBody: string;
		HTMLFullBody: string;
		CreateDate: Date;
		CCs: string;
		Bcc: string;
		InternalUsers: string;
		Direction: string;
		InboundEmailId: string;
		CommunicationLogId: string;
		EntityLineId: string;
	
}