//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class LastRunDetailList {
   
	Id: string;
	Tenant: number;
	LastRunDate: Date;
	LastRunByUserId: string;
	LastRunByUserName: string;
	
}
 