//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class MoveTypeList {
   		Id: string;
		Tenant: number;
		MoveTypeEnglishName: string;
		MoveTypeLocalName: string;
		TransportModeId: string;
		AddedManually: boolean;
		InActive: boolean;
		Code: string;
		SearchFields: string;
		IsAir: boolean;
		IsInland: boolean;
		IsOcean: boolean;
	
}