//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class TasksSchedulerList {
   		Id: string;
		Tenant: number;
		CreateDateTime: Date;
		CreatedBy: string;
		UpdateDateTime: Date;
		UpdatedBy: string;
		Name: string;
		Description: string;
		NextRunTime: Date;
		LastRunResult: string;
		InActive: boolean;
		ProcedureCode: string;
		TriggerType: string;
		Satarday: boolean;
		Sunday: boolean;
		Monday: boolean;
		Tuesday: boolean;
		Wednesday: boolean;
		Thursday: boolean;
		Friday: boolean;
		MonthlyDay: number;
		StartDateTime: Date;
		RepeatInMinutes: number;
		IsLastRunError: boolean;
		Type: string;
		NextRunTimeUTC: Date;
		StartDateTimeUTC: Date;
		LastRunEndTime: Date;
		LastRunEndTimeUTC: Date;
		LastRunStartTimeUTC: Date;
		LastRunStartTime: Date;
		Version: number;
		Status: string;
		Retries: number;
		AverageRunTime: number;
		EntityId: string;
		Recepients: string;
		ResultType: string;
		Format: string;
		AdvancedFormat: string;
	
}