//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class TaskSchedulerHistoryList {
   		Id: string;
		Tenant: number;
		StartDateTime: Date;
		EndDateTime: Date;
		RunResult: string;
		TaskId: string;
		IsError: boolean;
		StartDateTimeUTC: Date;
		EndDateTimeUTC: Date;
		LogType: string;
		LogFirstLine: string;
		Duration: number;
		LogDocumentId: string;
	
}