//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class TeamList {
   
	Id: string;
	Tenant: number;
	CreateDate: Date;
	CreatedByUserId: string;
	UpdateDate: Date;
	UpdatedByUserId: string;
	SearchFields: string;
	Name: string;
	LocalName: string;
	InActive: boolean;
	ManagerUserId: string;
	ManagerUserName: string;
	Notify: string;
	Notes: string;
	
}
 