//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class TenantManagmentPrivateLabelsList {
   		Id: string;
		PrivateLabelName: string;
		PrivateLabelShortName: string;
		PrivateLabelUrl: string;
		PrivateLabelDomain: string;
		MainLogo: string;
		ContactUsEmail: string;
		ReceiveAllStatuses: boolean;
		HybridPartnerId: string;
		InActive: boolean;
		SearchFields: string;
		SmallLogo: string;
		BackgroundImageId: string;
		LoginImageId: string;
		MainColor: string;
		LoginProgressImageId: string;
		ForgetPasswordImageId: string;
		SecondaryColor: string;
		HasLogboxAccess: boolean;
	
}