//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class VolumeUnitList {
   		Code: string;
		Name: string;
		PrintAs: string;
		SearchFields: string;
	
}