//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class WebhookKeysList {
   		Id: string;
		AccessKey: string;
		Tenant: number;
		PartnerName: string;
		InActive: boolean;
		CreatedByUserName: string;
		CreateDate: Date;
		UpdatedByUserName: string;
		UpdateDate: Date;
		Description: string;
		SearchFields: string;
	
}